apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: web-app
    count: 4

images:
  - name: nginx
    newName: nginx
    newTag: 1.25.3

commonLabels:
  env: production
